# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00bb82a2f9f9849e1fa9f39ac8d46c864da19c124ea1d143537bf0dc002ff822109902578bffc8835fe3197a921b65c61079b1a9cd253bced31df61e04f0fdf3

test:
  secret_key_base: 345dcc3c11cd4653e4608c76fe92c01cc036e718675faaa75cbbf66da49b03250d181e77280723f381c4729a6497ec443185d6be070eda5bc62316add7e6ebda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
